Replace Loki with Vali
gardener/logging pull request #166
Opened 2023-01-19 14:59 UTC by Kristian-ZH

**How to categorize this PR?**

/kind enhancement
/area logging

**What this PR does / why we need it**:
This PR replaces Loki with Vali

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
@vlvasilev 

**Release note**:

```other operator
Loki is now replaced with Vali: https://github.com/credativ/vali
```

2023-01-19 16:22 UTC, istvanballok reviewed
/lgtm

2023-01-23 11:34 UTC, nickytd commented
/lgtm

2023-01-24 07:57 UTC, vlvasilev approved these changes
/lgtm

2023-03-07 09:35 UTC, vlvasilev requested changes
except the version postfix all is lgtm

2023-03-08 09:21 UTC, Kristian-ZH commented on VERSION
> +v0.49.0-dev-vali-3
my bad, that is a leftover from the local testing

2023-05-04 07:12 UTC, closed without merging